# Generated by Django 4.0.6 on 2022-10-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PP', 'Peer to Peer'), ('GR', 'Group')], default='PP', max_length=2)),
                ('title', models.CharField(default='lobby', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/group_images')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.community')),
                ('participants', models.ManyToManyField(related_name='room_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_xp', models.PositiveBigIntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('final_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('F', 'File'), ('P', 'Post'), ('C', 'Community')], default='T', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/text_images')),
                ('file', models.FileField(blank=True, null=True, upload_to='public/text_files')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_community', to='subjects.community')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_post', to='blog.masterpost')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='message_seen_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
