# Generated by Django 4.0.6 on 2022-10-12 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
        migrations.AddField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(related_name='room_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
