# Generated by Django 4.0.6 on 2022-10-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/subject_pics')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='public/subject_banners')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('interests', models.ManyToManyField(blank=True, related_name='user_interests', to='blog.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/subject_pics')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='public/subject_banners')),
                ('short_description', models.CharField(max_length=200)),
                ('master_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.community')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
