# Generated by Django 4.0.6 on 2022-10-10 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='public/form_files')),
                ('sent_token', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('PO', 'Post'), ('PR', 'Project'), ('EV', 'Event')], default='PO', max_length=2)),
                ('privacy', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Only Followers'), (2, 'Only Community Members')], default=0)),
                ('title', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('region_details', models.JSONField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/post_images')),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='public/post_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])])),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('masterpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.masterpost')),
                ('type', models.CharField(max_length=3)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('form_data', models.JSONField(blank=True, null=True)),
            ],
            bases=('blog.masterpost',),
        ),
        migrations.CreateModel(
            name='FundablePost',
            fields=[
                ('masterpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.masterpost')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('target', models.PositiveBigIntegerField()),
                ('current', models.PositiveBigIntegerField(default=0)),
                ('total_funded', models.PositiveBigIntegerField(default=0)),
                ('minimum_fundable_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('form_data', models.JSONField()),
            ],
            bases=('blog.masterpost',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('posts', models.ManyToManyField(blank=True, related_name='tag_posts', to='blog.masterpost')),
            ],
        ),
    ]
