# Generated by Django 4.0.6 on 2022-10-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpost',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.community'),
        ),
        migrations.AddField(
            model_name='masterpost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='post_images', to='blog.postimage'),
        ),
        migrations.AddField(
            model_name='masterpost',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='post_videos', to='blog.postvideo'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_response', to='blog.masterpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.masterpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.comment'),
        ),
        migrations.AddField(
            model_name='fundablepost',
            name='contributers',
            field=models.ManyToManyField(blank=True, related_name='contributers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='attendies',
            field=models.ManyToManyField(blank=True, related_name='attendies', to=settings.AUTH_USER_MODEL),
        ),
    ]
