# Generated by Django 4.0.6 on 2022-10-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('verified_state', models.CharField(choices=[('N', 'None'), ('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('from_addr', models.CharField(max_length=200)),
                ('to_addr', models.CharField(max_length=200)),
                ('verified_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityWallet',
            fields=[
                ('wallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chain.wallet')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subjects.community')),
            ],
            bases=('chain.wallet',),
        ),
        migrations.CreateModel(
            name='ChainPage',
            fields=[
                ('wallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chain.wallet')),
                ('xp', models.PositiveBigIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('staked_level', models.PositiveIntegerField(default=0)),
                ('verifications', models.PositiveIntegerField(default=0)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='id_images')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='id_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chain.wallet',),
        ),
    ]
